PROJECT_NAME = Employee_Record_System

#All Source code file
#Path to the header file
INC_HEADER = inc
 
SRC = main.c
INC = fun.h

all.out : $(SRC)
	gcc $^ -o $@

run: target
	./all.out

clean:
	rm all.out